import platform
import uuid
import hashlib
import os

def get_mac_address():
    """Gets the MAC Address of the current machine deterministically."""
    
    # On Linux, interface names can change during boot (e.g., eth0 -> end0).
    # To be 100% deterministic, we collect ALL hardware MAC addresses, 
    # sort them, and pick the first one. This guarantees the same MAC is chosen 
    # regardless of whether it's called eth0, wlan0, or end0.
    if platform.system() == "Linux":
        macs = []
        try:
            for iface in os.listdir('/sys/class/net/'):
                # Ignore loopback and common virtual adapters
                if iface == 'lo' or iface.startswith('veth') or iface.startswith('docker') or iface.startswith('br-'):
                    continue
                    
                path = f"/sys/class/net/{iface}/address"
                if os.path.exists(path):
                    with open(path, 'r') as f:
                        mac = f.read().strip().upper()
                        if mac and mac != "00:00:00:00:00:00" and mac not in macs:
                            macs.append(mac)
                            
            if macs:
                macs.sort() # Alphabetical sort guarantees the same MAC is always picked
                return macs[0]
        except Exception as e:
            print(f"Fallback reading MAC: {e}")

    try:
        # Fallback for Windows/Mac (Not RPi)
        mac_num = uuid.getnode()
        # If the multicast bit is set, the MAC is randomly generated by Python
        if (mac_num >> 40) & 1:
            return "NO_PHYSICAL_MAC_FOUND"
            
        mac_str = ':'.join(('%012X' % mac_num)[i:i+2] for i in range(0, 12, 2))
        return mac_str
    except Exception as e:
        print(f"Failed to get MAC address: {e}")
        return "UNKNOWN_MAC"

def get_cpu_serial():
    """Extracts the unique hardware serial from /proc/cpuinfo (Raspberry Pi only)."""
    if platform.system() != "Linux":
        # On Windows/Mac (e.g. for local testing), return a mock serial
        return "DEV_MACHINE_SERIAL_001"
        
    try:
        with open('/proc/cpuinfo', 'r') as f:
            for line in f:
                if line.startswith('Serial'):
                    # E.g. Serial          : 0000000000123456
                    parts = line.split(':')
                    if len(parts) == 2:
                        return parts[1].strip()
        return "NO_SERIAL_FOUND"
    except Exception as e:
        print(f"Failed to get CPU serial: {e}")
        return "ERROR_READING_SERIAL"

def get_hardware_passphrase():
    """
    Derives a deterministic, strong passphrase from the physical device's CPU serial.
    This passphrase will unlock the private.pem file.
    """
    serial = get_cpu_serial()
    
    # If a real CPU Serial is found (Raspberry Pi), strictly use it for perfection
    if serial not in ("DEV_MACHINE_SERIAL_001", "NO_SERIAL_FOUND", "ERROR_READING_SERIAL"):
        raw_identity = f"EVM_SECURE_RPI_{serial}"
    else:
        # Fallback for Dev Machines/VMs
        mac = get_mac_address()
        raw_identity = f"EVM_SECURE_{mac}_{serial}"
    
    # Hash it to ensure a consistent, strong passphrase length
    passphrase = hashlib.sha256(raw_identity.encode('utf-8')).hexdigest()
    return passphrase.encode('utf-8')

if __name__ == "__main__":
    print(f"MAC Address: {get_mac_address()}")
    print(f"CPU Serial: {get_cpu_serial()}")
    print(f"Derived Passphrase (SHA256): {get_hardware_passphrase().decode('utf-8')}")
